CC = /usr/bin/gcc
CFLAGS = -g -O0 -fopenmp
LD = /usr/bin/gcc
LDFLAGS = -g -fopenmp

PROGRAM = frequencyOMP

all:	${PROGRAM}.exe

${PROGRAM}.exe: ${PROGRAM}.o
	${LD} ${LDFLAGS} $< -o ${PROGRAM}.exe

${PROGRAM}.o: ${PROGRAM}.c
	${CC} ${CFLAGS} -c $< -o ${PROGRAM}.o

clean:
	rm -f ${PROGRAM}.o ${PROGRAM}.exe
